locale: en

logging:
  error:
    enabled: true
  debug:
    enabled: true
  info:
    enabled: true
  db:
    enabled: true
    level: error # info, warn, error, silent
    color: true
    slow_query: 50ms

chat:
  buffer: 10000

database:
  driver: sqlite
  sqlite:
    path: ./db/database.sqlite

password:
  driver: bcrypt
  bcrypt:
    cost: 10
