locale: en

logging:
  error:
    enabled: true
  debug:
    enabled: true
  info:
    enabled: true
  db:
    enabled: true
    level: error # info, warn, error, silent
    color: true
    slow_query: 50ms

chat:
  buffer: 10000

database:
  driver: postgres
  sqlite:
    path: './db/database.sqlite'
    max_idle_connections: 10
    max_open_connections: 100
    conn_max_lifetime: 24h
    max_idle_lifetime: 1h
  postgres:
    dsn: 'host=localhost user=chat_app password=chat_app dbname=chat_app port=5432 sslmode=disable TimeZone=UTC'
    max_idle_connections: 10
    max_open_connections: 100
    conn_max_lifetime: 24h
    max_idle_lifetime: 1h

password:
  driver: bcrypt
  bcrypt:
    cost: 10
auth:
  allowed:
  blocked:
    - /pb.Chat/SendMessage
    - /pb.Chat/Connect
    - /pb.Auth/Logout